### ISSUE TITLE
Open and close sounds stop working after refresh

### ISSUE THREAD

**Issue by Rinzlers** [EndlesNights/ambientdoors#1]
The module works well on the initial config for open and close sounds.  The sounds stop working after the scene is refreshed.  I need to open the door config page, select a sound, and save to fix the issue.  After a new scene is loaded, I need to rinse and repeat.

**Comment by AtreidesGhola** [comment]
Same here - set doors last night on a map, around 20 or so.  Came back today to finish walls and lighting on the map, and most doors only have two sounds (Either open or close, and then lock or unlock).  To correct this, I have to enter a door dialogue for each door again and reset the sounds.

**Comment by EndlesNights** [comment]
Thanks, I have identified the issue where the data was not saving correctly and I am currently fixing the issue while reworking some other aspects. A new version 2.0.0 should be available soon.

**Comment by Rinzlers** [comment]
Awesome! Thanks for the update.

**Comment by AtreidesGhola** [comment]
That’s awesome, thanks!  My players had their first session in Foundry VTT the night I posted, and they loved everything, but the doors were a huge hit from the beginning. Especially once they hit their first locked door.

**Comment by Rinzlers** [comment]
I just tried the update.  I cannot seem to get the module to work at all now.
1. When it is enabled, I can no longer zoom in or out on the map.
2. I cannot edit or create walls or doors.
3. No sound path option is visible in the wall properties window.

**Comment by EndlesNights** [comment]
I had accidentally uploaded wrong version, I think you might have tried using that version. Would you mind trying the current version again please?

**Comment by Rinzlers** [comment]
Absolutely.  One minute

**Comment by Rinzlers** [comment]
Cool! It is working
I just logged out and logged back in and the doors saved their settings.
Thanks again!

**Comment by EndlesNights** [comment]
Alright great! I made some other changes as well that you can see the readme.
PS. If you happen across another other good door royalty free SFX feel free to message me as I'm planning on putting together a small sound library for people to use.
