### ISSUE TITLE
Just a minor issue for Linux Users

### ISSUE THREAD

**Issue by Eldintux** [EndlesNights/ambientdoors#12]
This module uses the alt key to 'steath' opening & closing doors. The alt key has other using in the Linux operating system which mean I cannot access this facility. I could find a way of changing it other than going into the module & changing the coding. This is OK but I will have to do it over again when an update is issued. Any chance that a facility to use an alternative to the alt key could be built in please?

**Comment by EndlesNights** [comment]
Sorry it took so long to get to this, but v9 made with super for user to be able to set their own custom hotkeys.
