### ISSUE TITLE
Issues when used in combination with Designer Doors

### ISSUE THREAD

**Issue by Gurrgel** [EndlesNights/ambientdoors#19]
When I have the module Designer Doors active as well as Ambient Doors, I encounter issues when trying to set the sounds for an individual door. Whenever I click the button to open the filepicker, two windows open, one behind the other, and since they're both opened and meant to change the same sound, it gets somewhat confusing if you change the sound file from the first window, but then accidently click the select file button for the second window which still has DefaultSound selected (and as a reminder, was hidden right underneath the first window up until now), you change back to the default sound, so you have to select the sound with the first window and then press the x to close the second window to actually change a sound.

I've confirmed this with Find the Culprit and only Designer Doors, Ambient Doors and LibWrapper active. No errors in the console, other than the fact that the RenderFilePicker line is run twice.

Using version 9.269 of Foundry, DnD 5e v 1.6.1, Ambient Doors v 2.2.6 and designer Doors 3.0.0

**Comment by EndlesNights** [comment]
Little slow to get around to this, but this should be fixed now as of the latest version.
