### ISSUE TITLE
Unlock sound does not work in unix filesystems due to name mismatch

### ISSUE THREAD

**Issue by Alarich** [EndlesNights/ambientdoors#2]
Hey there. Someone recently found a bug where the unlock sound works in windows, but not on The Forge. 

The reason being is that the filename for door unlock sound file is called `DoorUnlockSound.wav`, while the js file is asking for `DoorUnLockSound.wav`, which does not exist.

**Comment by EndlesNights** [comment]
Whooops, I see the issue and it has now been fixed.

**Comment by Jairlyn** [comment]
Hello. I was the one that reported the bug. Just wanted to give a thank you for the quick fix and thank you for the mod. It adds a good amount of atmosphere and feedback for how my players are interacting with the maps! We are really enjoying it.
