### ISSUE TITLE
(Almost) No sounds with 2.3.0 in v10

### ISSUE THREAD

**Issue by rdefendi** [EndlesNights/ambientdoors#21]
With 2.3.0 in v10, I can't get any sounds to play. I'm on the current version 288. I've tried in both D&D 5e and Aliens RPG, so it doesn't seem system dependent. It occurs with no other modules running. In console, I see the following error:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/11877369/200089669-423da2e2-7ec6-474e-a053-9474ddcdeaae.png">

**Comment by rdefendi** [comment]
Sorry, the "Locked" sound plays, it all the others that fail.

**Comment by EndlesNights** [comment]
Have you by chance deleted the `Quiet Door Hotkey` key bindings?

**Comment by rdefendi** [comment]
Not intentionally, but there wasn't one. Adding one seems to have corrected it. Aliens was a fresh install, I thought. At any rate, adding one corrected it.
