### ISSUE TITLE
Trying to update Modual

### ISSUE THREAD

**Issue by HippyCraig** [EndlesNights/ambientdoors#3]
I have updated my Foundry VTT to 0.7.5, and I noticed this since then I dont think its specific but though worth mentioning.  I get the following when trying to update.

![image](https://user-images.githubusercontent.com/17074456/96898098-55dd1b80-145d-11eb-95af-1525548ac84c.png)

**Comment by DeadlyArtist** [comment]
![image](https://user-images.githubusercontent.com/44524817/96911793-9eb6c380-14a1-11eb-85fe-31efedc77cbe.png)

I think i got the same (or related) problem.

**Comment by EndlesNights** [comment]
I did a slight change to the manifest pathway. The solution would be to uninstall the module and reinstall it.

**Comment by HippyCraig** [comment]
Great thanks uninstalling and reinstalling worked
