### ISSUE TITLE
Error on 0.7.5

### ISSUE THREAD

**Issue by brunocalado** [EndlesNights/ambientdoors#4]
Hi.

0.7.5 has an error. Can you fix it? 

Thank you.
![image](https://user-images.githubusercontent.com/4999783/97083404-11c95280-15e6-11eb-978b-d5fc3bdb77a8.png)

**Comment by EndlesNights** [comment]
I did a slight change to the manifest pathway. The solution would be to uninstall the module and reinstall it. Sorry for the inconveniences.
