### ISSUE TITLE
Update ambientdoors v2.0.2 > Invalid json response body

### ISSUE THREAD

**Issue by dmpunks** [EndlesNights/ambientdoors#7]
On Foundry 0.7.5, I'm trying to update this mod (from v2.0.2) and I'm getting this error on "Invalid json response body" (screenshot attached)
![Screenshot 2020-11-07 094850](https://user-images.githubusercontent.com/1963509/98428868-89b37480-20de-11eb-944a-960b71dbf5ff.jpg)

**Comment by EndlesNights** [comment]
Uninstall & Reinstall the module.
